apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sw-block-dynamic
provisioner: block.csi.seaweedfs.com
volumeBindingMode: Immediate
allowVolumeExpansion: false
parameters:
  replicationFactor: "1"
