// Master-volume control-plane RPC for the block system.
//
// Direction:
//   volume -> master:   ObservationService.ReportHeartbeat (unary)
//   volume -> master:   AssignmentService.SubscribeAssignments (server-streaming)
//   operator -> master: EvidenceService.QueryVolumeStatus (unary, read-only)
//
// Boundary (T0 sketch §3 load-bearing):
//   - no message carries an AssignmentAsk
//   - no message field maps to Epoch / EndpointVersion as an INPUT from the volume side
//   - Epoch / EndpointVersion appear only INSIDE AssignmentFact, which is master-minted and
//     consumed by the volume read-only
//   - AssignmentFact has NO Intent field; Intent lives on AssignmentAsk, internal to the
//     authority package, and never crosses the wire

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: control.proto

package control

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ObservationService_ReportHeartbeat_FullMethodName = "/seaweedfs.block.control.ObservationService/ReportHeartbeat"
)

// ObservationServiceClient is the client API for ObservationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ObservationServiceClient interface {
	// Periodic unary heartbeat. Master validates, converts to
	// authority.HeartbeatMessage, calls ObservationHost.Ingest.
	// Ack is diagnostic only.
	ReportHeartbeat(ctx context.Context, in *HeartbeatReport, opts ...grpc.CallOption) (*HeartbeatAck, error)
}

type observationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewObservationServiceClient(cc grpc.ClientConnInterface) ObservationServiceClient {
	return &observationServiceClient{cc}
}

func (c *observationServiceClient) ReportHeartbeat(ctx context.Context, in *HeartbeatReport, opts ...grpc.CallOption) (*HeartbeatAck, error) {
	out := new(HeartbeatAck)
	err := c.cc.Invoke(ctx, ObservationService_ReportHeartbeat_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ObservationServiceServer is the server API for ObservationService service.
// All implementations must embed UnimplementedObservationServiceServer
// for forward compatibility
type ObservationServiceServer interface {
	// Periodic unary heartbeat. Master validates, converts to
	// authority.HeartbeatMessage, calls ObservationHost.Ingest.
	// Ack is diagnostic only.
	ReportHeartbeat(context.Context, *HeartbeatReport) (*HeartbeatAck, error)
	mustEmbedUnimplementedObservationServiceServer()
}

// UnimplementedObservationServiceServer must be embedded to have forward compatible implementations.
type UnimplementedObservationServiceServer struct {
}

func (UnimplementedObservationServiceServer) ReportHeartbeat(context.Context, *HeartbeatReport) (*HeartbeatAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportHeartbeat not implemented")
}
func (UnimplementedObservationServiceServer) mustEmbedUnimplementedObservationServiceServer() {}

// UnsafeObservationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ObservationServiceServer will
// result in compilation errors.
type UnsafeObservationServiceServer interface {
	mustEmbedUnimplementedObservationServiceServer()
}

func RegisterObservationServiceServer(s grpc.ServiceRegistrar, srv ObservationServiceServer) {
	s.RegisterService(&ObservationService_ServiceDesc, srv)
}

func _ObservationService_ReportHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObservationServiceServer).ReportHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObservationService_ReportHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObservationServiceServer).ReportHeartbeat(ctx, req.(*HeartbeatReport))
	}
	return interceptor(ctx, in, info, handler)
}

// ObservationService_ServiceDesc is the grpc.ServiceDesc for ObservationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ObservationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "seaweedfs.block.control.ObservationService",
	HandlerType: (*ObservationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportHeartbeat",
			Handler:    _ObservationService_ReportHeartbeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "control.proto",
}

const (
	AssignmentService_SubscribeAssignments_FullMethodName = "/seaweedfs.block.control.AssignmentService/SubscribeAssignments"
)

// AssignmentServiceClient is the client API for AssignmentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AssignmentServiceClient interface {
	// Server-streaming. Master sends the current volume
	// authority line on subscribe (catch-up) and every mint
	// thereafter. Current-line replay on fresh subscribe is
	// permitted (T0 sketch §8.2.1 test 3); per-(Epoch,
	// EndpointVersion) dedupe inside the master ensures the
	// client never sees the same line twice or in reverse
	// order, while RefreshEndpoint (same Epoch, higher
	// EndpointVersion) still flows through.
	SubscribeAssignments(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (AssignmentService_SubscribeAssignmentsClient, error)
}

type assignmentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAssignmentServiceClient(cc grpc.ClientConnInterface) AssignmentServiceClient {
	return &assignmentServiceClient{cc}
}

func (c *assignmentServiceClient) SubscribeAssignments(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (AssignmentService_SubscribeAssignmentsClient, error) {
	stream, err := c.cc.NewStream(ctx, &AssignmentService_ServiceDesc.Streams[0], AssignmentService_SubscribeAssignments_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &assignmentServiceSubscribeAssignmentsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AssignmentService_SubscribeAssignmentsClient interface {
	Recv() (*AssignmentFact, error)
	grpc.ClientStream
}

type assignmentServiceSubscribeAssignmentsClient struct {
	grpc.ClientStream
}

func (x *assignmentServiceSubscribeAssignmentsClient) Recv() (*AssignmentFact, error) {
	m := new(AssignmentFact)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AssignmentServiceServer is the server API for AssignmentService service.
// All implementations must embed UnimplementedAssignmentServiceServer
// for forward compatibility
type AssignmentServiceServer interface {
	// Server-streaming. Master sends the current volume
	// authority line on subscribe (catch-up) and every mint
	// thereafter. Current-line replay on fresh subscribe is
	// permitted (T0 sketch §8.2.1 test 3); per-(Epoch,
	// EndpointVersion) dedupe inside the master ensures the
	// client never sees the same line twice or in reverse
	// order, while RefreshEndpoint (same Epoch, higher
	// EndpointVersion) still flows through.
	SubscribeAssignments(*SubscribeRequest, AssignmentService_SubscribeAssignmentsServer) error
	mustEmbedUnimplementedAssignmentServiceServer()
}

// UnimplementedAssignmentServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAssignmentServiceServer struct {
}

func (UnimplementedAssignmentServiceServer) SubscribeAssignments(*SubscribeRequest, AssignmentService_SubscribeAssignmentsServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeAssignments not implemented")
}
func (UnimplementedAssignmentServiceServer) mustEmbedUnimplementedAssignmentServiceServer() {}

// UnsafeAssignmentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AssignmentServiceServer will
// result in compilation errors.
type UnsafeAssignmentServiceServer interface {
	mustEmbedUnimplementedAssignmentServiceServer()
}

func RegisterAssignmentServiceServer(s grpc.ServiceRegistrar, srv AssignmentServiceServer) {
	s.RegisterService(&AssignmentService_ServiceDesc, srv)
}

func _AssignmentService_SubscribeAssignments_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AssignmentServiceServer).SubscribeAssignments(m, &assignmentServiceSubscribeAssignmentsServer{stream})
}

type AssignmentService_SubscribeAssignmentsServer interface {
	Send(*AssignmentFact) error
	grpc.ServerStream
}

type assignmentServiceSubscribeAssignmentsServer struct {
	grpc.ServerStream
}

func (x *assignmentServiceSubscribeAssignmentsServer) Send(m *AssignmentFact) error {
	return x.ServerStream.SendMsg(m)
}

// AssignmentService_ServiceDesc is the grpc.ServiceDesc for AssignmentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AssignmentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "seaweedfs.block.control.AssignmentService",
	HandlerType: (*AssignmentServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeAssignments",
			Handler:       _AssignmentService_SubscribeAssignments_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "control.proto",
}

const (
	EvidenceService_QueryVolumeStatus_FullMethodName = "/seaweedfs.block.control.EvidenceService/QueryVolumeStatus"
)

// EvidenceServiceClient is the client API for EvidenceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EvidenceServiceClient interface {
	QueryVolumeStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type evidenceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEvidenceServiceClient(cc grpc.ClientConnInterface) EvidenceServiceClient {
	return &evidenceServiceClient{cc}
}

func (c *evidenceServiceClient) QueryVolumeStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, EvidenceService_QueryVolumeStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EvidenceServiceServer is the server API for EvidenceService service.
// All implementations must embed UnimplementedEvidenceServiceServer
// for forward compatibility
type EvidenceServiceServer interface {
	QueryVolumeStatus(context.Context, *StatusRequest) (*StatusResponse, error)
	mustEmbedUnimplementedEvidenceServiceServer()
}

// UnimplementedEvidenceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEvidenceServiceServer struct {
}

func (UnimplementedEvidenceServiceServer) QueryVolumeStatus(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryVolumeStatus not implemented")
}
func (UnimplementedEvidenceServiceServer) mustEmbedUnimplementedEvidenceServiceServer() {}

// UnsafeEvidenceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EvidenceServiceServer will
// result in compilation errors.
type UnsafeEvidenceServiceServer interface {
	mustEmbedUnimplementedEvidenceServiceServer()
}

func RegisterEvidenceServiceServer(s grpc.ServiceRegistrar, srv EvidenceServiceServer) {
	s.RegisterService(&EvidenceService_ServiceDesc, srv)
}

func _EvidenceService_QueryVolumeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EvidenceServiceServer).QueryVolumeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EvidenceService_QueryVolumeStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EvidenceServiceServer).QueryVolumeStatus(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EvidenceService_ServiceDesc is the grpc.ServiceDesc for EvidenceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EvidenceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "seaweedfs.block.control.EvidenceService",
	HandlerType: (*EvidenceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryVolumeStatus",
			Handler:    _EvidenceService_QueryVolumeStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "control.proto",
}
