// Master-volume control-plane RPC for the block system.
//
// Direction:
//   volume -> master:   ObservationService.ReportHeartbeat (unary)
//   volume -> master:   AssignmentService.SubscribeAssignments (server-streaming)
//   operator -> master: EvidenceService.QueryVolumeStatus (unary, read-only)
//   operator/dashboard -> master: ClusterEvidenceService read-only observation
//   CSI/operator -> master: LifecycleService.CreateVolume/DeleteVolume (desired intent only)
//   CSI/snapshot client -> master dedicated mTLS listener: SnapshotService catalog operations
//
// Boundary (T0 sketch §3 load-bearing):
//   - no message carries an AssignmentAsk
//   - no message field maps to Epoch / EndpointVersion as an INPUT from the volume side
//   - Epoch / EndpointVersion appear only INSIDE AssignmentFact, which is master-minted and
//     consumed by the volume read-only
//   - AssignmentFact has NO Intent field; Intent lives on AssignmentAsk, internal to the
//     authority package, and never crosses the wire

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: control.proto

package control

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ObservationService_ReportHeartbeat_FullMethodName    = "/seaweedfs.block.control.ObservationService/ReportHeartbeat"
	ObservationService_ReportClusterEvent_FullMethodName = "/seaweedfs.block.control.ObservationService/ReportClusterEvent"
)

// ObservationServiceClient is the client API for ObservationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ObservationServiceClient interface {
	// Periodic unary heartbeat. Master validates, converts to
	// authority.HeartbeatMessage, calls ObservationHost.Ingest.
	// Ack is diagnostic only.
	ReportHeartbeat(ctx context.Context, in *HeartbeatReport, opts ...grpc.CallOption) (*HeartbeatAck, error)
	// Node/CSI observation event. This appends an operator timeline event only;
	// it MUST NOT mutate lifecycle, authority, placement, Kubernetes, or
	// replica state.
	ReportClusterEvent(ctx context.Context, in *ClusterEvent, opts ...grpc.CallOption) (*ClusterEventAck, error)
}

type observationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewObservationServiceClient(cc grpc.ClientConnInterface) ObservationServiceClient {
	return &observationServiceClient{cc}
}

func (c *observationServiceClient) ReportHeartbeat(ctx context.Context, in *HeartbeatReport, opts ...grpc.CallOption) (*HeartbeatAck, error) {
	out := new(HeartbeatAck)
	err := c.cc.Invoke(ctx, ObservationService_ReportHeartbeat_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *observationServiceClient) ReportClusterEvent(ctx context.Context, in *ClusterEvent, opts ...grpc.CallOption) (*ClusterEventAck, error) {
	out := new(ClusterEventAck)
	err := c.cc.Invoke(ctx, ObservationService_ReportClusterEvent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ObservationServiceServer is the server API for ObservationService service.
// All implementations must embed UnimplementedObservationServiceServer
// for forward compatibility
type ObservationServiceServer interface {
	// Periodic unary heartbeat. Master validates, converts to
	// authority.HeartbeatMessage, calls ObservationHost.Ingest.
	// Ack is diagnostic only.
	ReportHeartbeat(context.Context, *HeartbeatReport) (*HeartbeatAck, error)
	// Node/CSI observation event. This appends an operator timeline event only;
	// it MUST NOT mutate lifecycle, authority, placement, Kubernetes, or
	// replica state.
	ReportClusterEvent(context.Context, *ClusterEvent) (*ClusterEventAck, error)
	mustEmbedUnimplementedObservationServiceServer()
}

// UnimplementedObservationServiceServer must be embedded to have forward compatible implementations.
type UnimplementedObservationServiceServer struct {
}

func (UnimplementedObservationServiceServer) ReportHeartbeat(context.Context, *HeartbeatReport) (*HeartbeatAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportHeartbeat not implemented")
}
func (UnimplementedObservationServiceServer) ReportClusterEvent(context.Context, *ClusterEvent) (*ClusterEventAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportClusterEvent not implemented")
}
func (UnimplementedObservationServiceServer) mustEmbedUnimplementedObservationServiceServer() {}

// UnsafeObservationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ObservationServiceServer will
// result in compilation errors.
type UnsafeObservationServiceServer interface {
	mustEmbedUnimplementedObservationServiceServer()
}

func RegisterObservationServiceServer(s grpc.ServiceRegistrar, srv ObservationServiceServer) {
	s.RegisterService(&ObservationService_ServiceDesc, srv)
}

func _ObservationService_ReportHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObservationServiceServer).ReportHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObservationService_ReportHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObservationServiceServer).ReportHeartbeat(ctx, req.(*HeartbeatReport))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObservationService_ReportClusterEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObservationServiceServer).ReportClusterEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObservationService_ReportClusterEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObservationServiceServer).ReportClusterEvent(ctx, req.(*ClusterEvent))
	}
	return interceptor(ctx, in, info, handler)
}

// ObservationService_ServiceDesc is the grpc.ServiceDesc for ObservationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ObservationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "seaweedfs.block.control.ObservationService",
	HandlerType: (*ObservationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportHeartbeat",
			Handler:    _ObservationService_ReportHeartbeat_Handler,
		},
		{
			MethodName: "ReportClusterEvent",
			Handler:    _ObservationService_ReportClusterEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "control.proto",
}

const (
	AssignmentService_SubscribeAssignments_FullMethodName = "/seaweedfs.block.control.AssignmentService/SubscribeAssignments"
)

// AssignmentServiceClient is the client API for AssignmentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AssignmentServiceClient interface {
	// Server-streaming. Master sends the current volume
	// authority line on subscribe (catch-up) and every mint
	// thereafter. Current-line replay on fresh subscribe is
	// permitted (T0 sketch §8.2.1 test 3); per-(Epoch,
	// EndpointVersion) dedupe inside the master ensures the
	// client never sees the same line twice or in reverse
	// order, while RefreshEndpoint (same Epoch, higher
	// EndpointVersion) still flows through.
	SubscribeAssignments(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (AssignmentService_SubscribeAssignmentsClient, error)
}

type assignmentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAssignmentServiceClient(cc grpc.ClientConnInterface) AssignmentServiceClient {
	return &assignmentServiceClient{cc}
}

func (c *assignmentServiceClient) SubscribeAssignments(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (AssignmentService_SubscribeAssignmentsClient, error) {
	stream, err := c.cc.NewStream(ctx, &AssignmentService_ServiceDesc.Streams[0], AssignmentService_SubscribeAssignments_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &assignmentServiceSubscribeAssignmentsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AssignmentService_SubscribeAssignmentsClient interface {
	Recv() (*AssignmentFact, error)
	grpc.ClientStream
}

type assignmentServiceSubscribeAssignmentsClient struct {
	grpc.ClientStream
}

func (x *assignmentServiceSubscribeAssignmentsClient) Recv() (*AssignmentFact, error) {
	m := new(AssignmentFact)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AssignmentServiceServer is the server API for AssignmentService service.
// All implementations must embed UnimplementedAssignmentServiceServer
// for forward compatibility
type AssignmentServiceServer interface {
	// Server-streaming. Master sends the current volume
	// authority line on subscribe (catch-up) and every mint
	// thereafter. Current-line replay on fresh subscribe is
	// permitted (T0 sketch §8.2.1 test 3); per-(Epoch,
	// EndpointVersion) dedupe inside the master ensures the
	// client never sees the same line twice or in reverse
	// order, while RefreshEndpoint (same Epoch, higher
	// EndpointVersion) still flows through.
	SubscribeAssignments(*SubscribeRequest, AssignmentService_SubscribeAssignmentsServer) error
	mustEmbedUnimplementedAssignmentServiceServer()
}

// UnimplementedAssignmentServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAssignmentServiceServer struct {
}

func (UnimplementedAssignmentServiceServer) SubscribeAssignments(*SubscribeRequest, AssignmentService_SubscribeAssignmentsServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeAssignments not implemented")
}
func (UnimplementedAssignmentServiceServer) mustEmbedUnimplementedAssignmentServiceServer() {}

// UnsafeAssignmentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AssignmentServiceServer will
// result in compilation errors.
type UnsafeAssignmentServiceServer interface {
	mustEmbedUnimplementedAssignmentServiceServer()
}

func RegisterAssignmentServiceServer(s grpc.ServiceRegistrar, srv AssignmentServiceServer) {
	s.RegisterService(&AssignmentService_ServiceDesc, srv)
}

func _AssignmentService_SubscribeAssignments_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AssignmentServiceServer).SubscribeAssignments(m, &assignmentServiceSubscribeAssignmentsServer{stream})
}

type AssignmentService_SubscribeAssignmentsServer interface {
	Send(*AssignmentFact) error
	grpc.ServerStream
}

type assignmentServiceSubscribeAssignmentsServer struct {
	grpc.ServerStream
}

func (x *assignmentServiceSubscribeAssignmentsServer) Send(m *AssignmentFact) error {
	return x.ServerStream.SendMsg(m)
}

// AssignmentService_ServiceDesc is the grpc.ServiceDesc for AssignmentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AssignmentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "seaweedfs.block.control.AssignmentService",
	HandlerType: (*AssignmentServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeAssignments",
			Handler:       _AssignmentService_SubscribeAssignments_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "control.proto",
}

const (
	EvidenceService_QueryVolumeStatus_FullMethodName = "/seaweedfs.block.control.EvidenceService/QueryVolumeStatus"
)

// EvidenceServiceClient is the client API for EvidenceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EvidenceServiceClient interface {
	QueryVolumeStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type evidenceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEvidenceServiceClient(cc grpc.ClientConnInterface) EvidenceServiceClient {
	return &evidenceServiceClient{cc}
}

func (c *evidenceServiceClient) QueryVolumeStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, EvidenceService_QueryVolumeStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EvidenceServiceServer is the server API for EvidenceService service.
// All implementations must embed UnimplementedEvidenceServiceServer
// for forward compatibility
type EvidenceServiceServer interface {
	QueryVolumeStatus(context.Context, *StatusRequest) (*StatusResponse, error)
	mustEmbedUnimplementedEvidenceServiceServer()
}

// UnimplementedEvidenceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEvidenceServiceServer struct {
}

func (UnimplementedEvidenceServiceServer) QueryVolumeStatus(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryVolumeStatus not implemented")
}
func (UnimplementedEvidenceServiceServer) mustEmbedUnimplementedEvidenceServiceServer() {}

// UnsafeEvidenceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EvidenceServiceServer will
// result in compilation errors.
type UnsafeEvidenceServiceServer interface {
	mustEmbedUnimplementedEvidenceServiceServer()
}

func RegisterEvidenceServiceServer(s grpc.ServiceRegistrar, srv EvidenceServiceServer) {
	s.RegisterService(&EvidenceService_ServiceDesc, srv)
}

func _EvidenceService_QueryVolumeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EvidenceServiceServer).QueryVolumeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EvidenceService_QueryVolumeStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EvidenceServiceServer).QueryVolumeStatus(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EvidenceService_ServiceDesc is the grpc.ServiceDesc for EvidenceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EvidenceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "seaweedfs.block.control.EvidenceService",
	HandlerType: (*EvidenceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryVolumeStatus",
			Handler:    _EvidenceService_QueryVolumeStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "control.proto",
}

const (
	ClusterEvidenceService_GetClusterStatus_FullMethodName   = "/seaweedfs.block.control.ClusterEvidenceService/GetClusterStatus"
	ClusterEvidenceService_ListVolumes_FullMethodName        = "/seaweedfs.block.control.ClusterEvidenceService/ListVolumes"
	ClusterEvidenceService_GetVolumeStatus_FullMethodName    = "/seaweedfs.block.control.ClusterEvidenceService/GetVolumeStatus"
	ClusterEvidenceService_GetVolumeTimeline_FullMethodName  = "/seaweedfs.block.control.ClusterEvidenceService/GetVolumeTimeline"
	ClusterEvidenceService_WatchClusterEvents_FullMethodName = "/seaweedfs.block.control.ClusterEvidenceService/WatchClusterEvents"
)

// ClusterEvidenceServiceClient is the client API for ClusterEvidenceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClusterEvidenceServiceClient interface {
	GetClusterStatus(ctx context.Context, in *GetClusterStatusRequest, opts ...grpc.CallOption) (*ClusterStatusResponse, error)
	ListVolumes(ctx context.Context, in *ListVolumesRequest, opts ...grpc.CallOption) (*ListVolumesResponse, error)
	GetVolumeStatus(ctx context.Context, in *GetVolumeStatusRequest, opts ...grpc.CallOption) (*VolumeEvidence, error)
	GetVolumeTimeline(ctx context.Context, in *GetVolumeTimelineRequest, opts ...grpc.CallOption) (*VolumeTimelineResponse, error)
	WatchClusterEvents(ctx context.Context, in *WatchClusterEventsRequest, opts ...grpc.CallOption) (ClusterEvidenceService_WatchClusterEventsClient, error)
}

type clusterEvidenceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClusterEvidenceServiceClient(cc grpc.ClientConnInterface) ClusterEvidenceServiceClient {
	return &clusterEvidenceServiceClient{cc}
}

func (c *clusterEvidenceServiceClient) GetClusterStatus(ctx context.Context, in *GetClusterStatusRequest, opts ...grpc.CallOption) (*ClusterStatusResponse, error) {
	out := new(ClusterStatusResponse)
	err := c.cc.Invoke(ctx, ClusterEvidenceService_GetClusterStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterEvidenceServiceClient) ListVolumes(ctx context.Context, in *ListVolumesRequest, opts ...grpc.CallOption) (*ListVolumesResponse, error) {
	out := new(ListVolumesResponse)
	err := c.cc.Invoke(ctx, ClusterEvidenceService_ListVolumes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterEvidenceServiceClient) GetVolumeStatus(ctx context.Context, in *GetVolumeStatusRequest, opts ...grpc.CallOption) (*VolumeEvidence, error) {
	out := new(VolumeEvidence)
	err := c.cc.Invoke(ctx, ClusterEvidenceService_GetVolumeStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterEvidenceServiceClient) GetVolumeTimeline(ctx context.Context, in *GetVolumeTimelineRequest, opts ...grpc.CallOption) (*VolumeTimelineResponse, error) {
	out := new(VolumeTimelineResponse)
	err := c.cc.Invoke(ctx, ClusterEvidenceService_GetVolumeTimeline_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterEvidenceServiceClient) WatchClusterEvents(ctx context.Context, in *WatchClusterEventsRequest, opts ...grpc.CallOption) (ClusterEvidenceService_WatchClusterEventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &ClusterEvidenceService_ServiceDesc.Streams[0], ClusterEvidenceService_WatchClusterEvents_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &clusterEvidenceServiceWatchClusterEventsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ClusterEvidenceService_WatchClusterEventsClient interface {
	Recv() (*ClusterEvent, error)
	grpc.ClientStream
}

type clusterEvidenceServiceWatchClusterEventsClient struct {
	grpc.ClientStream
}

func (x *clusterEvidenceServiceWatchClusterEventsClient) Recv() (*ClusterEvent, error) {
	m := new(ClusterEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ClusterEvidenceServiceServer is the server API for ClusterEvidenceService service.
// All implementations must embed UnimplementedClusterEvidenceServiceServer
// for forward compatibility
type ClusterEvidenceServiceServer interface {
	GetClusterStatus(context.Context, *GetClusterStatusRequest) (*ClusterStatusResponse, error)
	ListVolumes(context.Context, *ListVolumesRequest) (*ListVolumesResponse, error)
	GetVolumeStatus(context.Context, *GetVolumeStatusRequest) (*VolumeEvidence, error)
	GetVolumeTimeline(context.Context, *GetVolumeTimelineRequest) (*VolumeTimelineResponse, error)
	WatchClusterEvents(*WatchClusterEventsRequest, ClusterEvidenceService_WatchClusterEventsServer) error
	mustEmbedUnimplementedClusterEvidenceServiceServer()
}

// UnimplementedClusterEvidenceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedClusterEvidenceServiceServer struct {
}

func (UnimplementedClusterEvidenceServiceServer) GetClusterStatus(context.Context, *GetClusterStatusRequest) (*ClusterStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClusterStatus not implemented")
}
func (UnimplementedClusterEvidenceServiceServer) ListVolumes(context.Context, *ListVolumesRequest) (*ListVolumesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListVolumes not implemented")
}
func (UnimplementedClusterEvidenceServiceServer) GetVolumeStatus(context.Context, *GetVolumeStatusRequest) (*VolumeEvidence, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVolumeStatus not implemented")
}
func (UnimplementedClusterEvidenceServiceServer) GetVolumeTimeline(context.Context, *GetVolumeTimelineRequest) (*VolumeTimelineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVolumeTimeline not implemented")
}
func (UnimplementedClusterEvidenceServiceServer) WatchClusterEvents(*WatchClusterEventsRequest, ClusterEvidenceService_WatchClusterEventsServer) error {
	return status.Errorf(codes.Unimplemented, "method WatchClusterEvents not implemented")
}
func (UnimplementedClusterEvidenceServiceServer) mustEmbedUnimplementedClusterEvidenceServiceServer() {
}

// UnsafeClusterEvidenceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClusterEvidenceServiceServer will
// result in compilation errors.
type UnsafeClusterEvidenceServiceServer interface {
	mustEmbedUnimplementedClusterEvidenceServiceServer()
}

func RegisterClusterEvidenceServiceServer(s grpc.ServiceRegistrar, srv ClusterEvidenceServiceServer) {
	s.RegisterService(&ClusterEvidenceService_ServiceDesc, srv)
}

func _ClusterEvidenceService_GetClusterStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClusterStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterEvidenceServiceServer).GetClusterStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterEvidenceService_GetClusterStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterEvidenceServiceServer).GetClusterStatus(ctx, req.(*GetClusterStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterEvidenceService_ListVolumes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVolumesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterEvidenceServiceServer).ListVolumes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterEvidenceService_ListVolumes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterEvidenceServiceServer).ListVolumes(ctx, req.(*ListVolumesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterEvidenceService_GetVolumeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVolumeStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterEvidenceServiceServer).GetVolumeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterEvidenceService_GetVolumeStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterEvidenceServiceServer).GetVolumeStatus(ctx, req.(*GetVolumeStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterEvidenceService_GetVolumeTimeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVolumeTimelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterEvidenceServiceServer).GetVolumeTimeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterEvidenceService_GetVolumeTimeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterEvidenceServiceServer).GetVolumeTimeline(ctx, req.(*GetVolumeTimelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterEvidenceService_WatchClusterEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchClusterEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ClusterEvidenceServiceServer).WatchClusterEvents(m, &clusterEvidenceServiceWatchClusterEventsServer{stream})
}

type ClusterEvidenceService_WatchClusterEventsServer interface {
	Send(*ClusterEvent) error
	grpc.ServerStream
}

type clusterEvidenceServiceWatchClusterEventsServer struct {
	grpc.ServerStream
}

func (x *clusterEvidenceServiceWatchClusterEventsServer) Send(m *ClusterEvent) error {
	return x.ServerStream.SendMsg(m)
}

// ClusterEvidenceService_ServiceDesc is the grpc.ServiceDesc for ClusterEvidenceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClusterEvidenceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "seaweedfs.block.control.ClusterEvidenceService",
	HandlerType: (*ClusterEvidenceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetClusterStatus",
			Handler:    _ClusterEvidenceService_GetClusterStatus_Handler,
		},
		{
			MethodName: "ListVolumes",
			Handler:    _ClusterEvidenceService_ListVolumes_Handler,
		},
		{
			MethodName: "GetVolumeStatus",
			Handler:    _ClusterEvidenceService_GetVolumeStatus_Handler,
		},
		{
			MethodName: "GetVolumeTimeline",
			Handler:    _ClusterEvidenceService_GetVolumeTimeline_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchClusterEvents",
			Handler:       _ClusterEvidenceService_WatchClusterEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "control.proto",
}

const (
	LifecycleService_CreateVolume_FullMethodName = "/seaweedfs.block.control.LifecycleService/CreateVolume"
	LifecycleService_DeleteVolume_FullMethodName = "/seaweedfs.block.control.LifecycleService/DeleteVolume"
)

// LifecycleServiceClient is the client API for LifecycleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LifecycleServiceClient interface {
	CreateVolume(ctx context.Context, in *CreateVolumeRequest, opts ...grpc.CallOption) (*CreateVolumeResponse, error)
	DeleteVolume(ctx context.Context, in *DeleteVolumeRequest, opts ...grpc.CallOption) (*DeleteVolumeResponse, error)
}

type lifecycleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLifecycleServiceClient(cc grpc.ClientConnInterface) LifecycleServiceClient {
	return &lifecycleServiceClient{cc}
}

func (c *lifecycleServiceClient) CreateVolume(ctx context.Context, in *CreateVolumeRequest, opts ...grpc.CallOption) (*CreateVolumeResponse, error) {
	out := new(CreateVolumeResponse)
	err := c.cc.Invoke(ctx, LifecycleService_CreateVolume_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lifecycleServiceClient) DeleteVolume(ctx context.Context, in *DeleteVolumeRequest, opts ...grpc.CallOption) (*DeleteVolumeResponse, error) {
	out := new(DeleteVolumeResponse)
	err := c.cc.Invoke(ctx, LifecycleService_DeleteVolume_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LifecycleServiceServer is the server API for LifecycleService service.
// All implementations must embed UnimplementedLifecycleServiceServer
// for forward compatibility
type LifecycleServiceServer interface {
	CreateVolume(context.Context, *CreateVolumeRequest) (*CreateVolumeResponse, error)
	DeleteVolume(context.Context, *DeleteVolumeRequest) (*DeleteVolumeResponse, error)
	mustEmbedUnimplementedLifecycleServiceServer()
}

// UnimplementedLifecycleServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLifecycleServiceServer struct {
}

func (UnimplementedLifecycleServiceServer) CreateVolume(context.Context, *CreateVolumeRequest) (*CreateVolumeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVolume not implemented")
}
func (UnimplementedLifecycleServiceServer) DeleteVolume(context.Context, *DeleteVolumeRequest) (*DeleteVolumeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteVolume not implemented")
}
func (UnimplementedLifecycleServiceServer) mustEmbedUnimplementedLifecycleServiceServer() {}

// UnsafeLifecycleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LifecycleServiceServer will
// result in compilation errors.
type UnsafeLifecycleServiceServer interface {
	mustEmbedUnimplementedLifecycleServiceServer()
}

func RegisterLifecycleServiceServer(s grpc.ServiceRegistrar, srv LifecycleServiceServer) {
	s.RegisterService(&LifecycleService_ServiceDesc, srv)
}

func _LifecycleService_CreateVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LifecycleServiceServer).CreateVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LifecycleService_CreateVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LifecycleServiceServer).CreateVolume(ctx, req.(*CreateVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LifecycleService_DeleteVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LifecycleServiceServer).DeleteVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LifecycleService_DeleteVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LifecycleServiceServer).DeleteVolume(ctx, req.(*DeleteVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LifecycleService_ServiceDesc is the grpc.ServiceDesc for LifecycleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LifecycleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "seaweedfs.block.control.LifecycleService",
	HandlerType: (*LifecycleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVolume",
			Handler:    _LifecycleService_CreateVolume_Handler,
		},
		{
			MethodName: "DeleteVolume",
			Handler:    _LifecycleService_DeleteVolume_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "control.proto",
}

const (
	FailbackService_ExecuteFailback_FullMethodName = "/seaweedfs.block.control.FailbackService/ExecuteFailback"
)

// FailbackServiceClient is the client API for FailbackService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FailbackServiceClient interface {
	ExecuteFailback(ctx context.Context, in *FailbackRequest, opts ...grpc.CallOption) (*FailbackResponse, error)
}

type failbackServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFailbackServiceClient(cc grpc.ClientConnInterface) FailbackServiceClient {
	return &failbackServiceClient{cc}
}

func (c *failbackServiceClient) ExecuteFailback(ctx context.Context, in *FailbackRequest, opts ...grpc.CallOption) (*FailbackResponse, error) {
	out := new(FailbackResponse)
	err := c.cc.Invoke(ctx, FailbackService_ExecuteFailback_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FailbackServiceServer is the server API for FailbackService service.
// All implementations must embed UnimplementedFailbackServiceServer
// for forward compatibility
type FailbackServiceServer interface {
	ExecuteFailback(context.Context, *FailbackRequest) (*FailbackResponse, error)
	mustEmbedUnimplementedFailbackServiceServer()
}

// UnimplementedFailbackServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFailbackServiceServer struct {
}

func (UnimplementedFailbackServiceServer) ExecuteFailback(context.Context, *FailbackRequest) (*FailbackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteFailback not implemented")
}
func (UnimplementedFailbackServiceServer) mustEmbedUnimplementedFailbackServiceServer() {}

// UnsafeFailbackServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FailbackServiceServer will
// result in compilation errors.
type UnsafeFailbackServiceServer interface {
	mustEmbedUnimplementedFailbackServiceServer()
}

func RegisterFailbackServiceServer(s grpc.ServiceRegistrar, srv FailbackServiceServer) {
	s.RegisterService(&FailbackService_ServiceDesc, srv)
}

func _FailbackService_ExecuteFailback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FailbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FailbackServiceServer).ExecuteFailback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FailbackService_ExecuteFailback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FailbackServiceServer).ExecuteFailback(ctx, req.(*FailbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FailbackService_ServiceDesc is the grpc.ServiceDesc for FailbackService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FailbackService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "seaweedfs.block.control.FailbackService",
	HandlerType: (*FailbackServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteFailback",
			Handler:    _FailbackService_ExecuteFailback_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "control.proto",
}

const (
	SnapshotService_CreateSnapshot_FullMethodName  = "/seaweedfs.block.control.SnapshotService/CreateSnapshot"
	SnapshotService_GetSnapshot_FullMethodName     = "/seaweedfs.block.control.SnapshotService/GetSnapshot"
	SnapshotService_ListSnapshots_FullMethodName   = "/seaweedfs.block.control.SnapshotService/ListSnapshots"
	SnapshotService_DeleteSnapshot_FullMethodName  = "/seaweedfs.block.control.SnapshotService/DeleteSnapshot"
	SnapshotService_RestoreSnapshot_FullMethodName = "/seaweedfs.block.control.SnapshotService/RestoreSnapshot"
)

// SnapshotServiceClient is the client API for SnapshotService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SnapshotServiceClient interface {
	CreateSnapshot(ctx context.Context, in *CreateSnapshotRequest, opts ...grpc.CallOption) (*SnapshotRecord, error)
	GetSnapshot(ctx context.Context, in *GetSnapshotRequest, opts ...grpc.CallOption) (*SnapshotRecord, error)
	ListSnapshots(ctx context.Context, in *ListSnapshotsRequest, opts ...grpc.CallOption) (*ListSnapshotsResponse, error)
	DeleteSnapshot(ctx context.Context, in *DeleteSnapshotRequest, opts ...grpc.CallOption) (*DeleteSnapshotResponse, error)
	RestoreSnapshot(ctx context.Context, in *RestoreSnapshotRequest, opts ...grpc.CallOption) (*RestoreSnapshotResponse, error)
}

type snapshotServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSnapshotServiceClient(cc grpc.ClientConnInterface) SnapshotServiceClient {
	return &snapshotServiceClient{cc}
}

func (c *snapshotServiceClient) CreateSnapshot(ctx context.Context, in *CreateSnapshotRequest, opts ...grpc.CallOption) (*SnapshotRecord, error) {
	out := new(SnapshotRecord)
	err := c.cc.Invoke(ctx, SnapshotService_CreateSnapshot_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snapshotServiceClient) GetSnapshot(ctx context.Context, in *GetSnapshotRequest, opts ...grpc.CallOption) (*SnapshotRecord, error) {
	out := new(SnapshotRecord)
	err := c.cc.Invoke(ctx, SnapshotService_GetSnapshot_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snapshotServiceClient) ListSnapshots(ctx context.Context, in *ListSnapshotsRequest, opts ...grpc.CallOption) (*ListSnapshotsResponse, error) {
	out := new(ListSnapshotsResponse)
	err := c.cc.Invoke(ctx, SnapshotService_ListSnapshots_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snapshotServiceClient) DeleteSnapshot(ctx context.Context, in *DeleteSnapshotRequest, opts ...grpc.CallOption) (*DeleteSnapshotResponse, error) {
	out := new(DeleteSnapshotResponse)
	err := c.cc.Invoke(ctx, SnapshotService_DeleteSnapshot_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snapshotServiceClient) RestoreSnapshot(ctx context.Context, in *RestoreSnapshotRequest, opts ...grpc.CallOption) (*RestoreSnapshotResponse, error) {
	out := new(RestoreSnapshotResponse)
	err := c.cc.Invoke(ctx, SnapshotService_RestoreSnapshot_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SnapshotServiceServer is the server API for SnapshotService service.
// All implementations must embed UnimplementedSnapshotServiceServer
// for forward compatibility
type SnapshotServiceServer interface {
	CreateSnapshot(context.Context, *CreateSnapshotRequest) (*SnapshotRecord, error)
	GetSnapshot(context.Context, *GetSnapshotRequest) (*SnapshotRecord, error)
	ListSnapshots(context.Context, *ListSnapshotsRequest) (*ListSnapshotsResponse, error)
	DeleteSnapshot(context.Context, *DeleteSnapshotRequest) (*DeleteSnapshotResponse, error)
	RestoreSnapshot(context.Context, *RestoreSnapshotRequest) (*RestoreSnapshotResponse, error)
	mustEmbedUnimplementedSnapshotServiceServer()
}

// UnimplementedSnapshotServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSnapshotServiceServer struct {
}

func (UnimplementedSnapshotServiceServer) CreateSnapshot(context.Context, *CreateSnapshotRequest) (*SnapshotRecord, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSnapshot not implemented")
}
func (UnimplementedSnapshotServiceServer) GetSnapshot(context.Context, *GetSnapshotRequest) (*SnapshotRecord, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSnapshot not implemented")
}
func (UnimplementedSnapshotServiceServer) ListSnapshots(context.Context, *ListSnapshotsRequest) (*ListSnapshotsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSnapshots not implemented")
}
func (UnimplementedSnapshotServiceServer) DeleteSnapshot(context.Context, *DeleteSnapshotRequest) (*DeleteSnapshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSnapshot not implemented")
}
func (UnimplementedSnapshotServiceServer) RestoreSnapshot(context.Context, *RestoreSnapshotRequest) (*RestoreSnapshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestoreSnapshot not implemented")
}
func (UnimplementedSnapshotServiceServer) mustEmbedUnimplementedSnapshotServiceServer() {}

// UnsafeSnapshotServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SnapshotServiceServer will
// result in compilation errors.
type UnsafeSnapshotServiceServer interface {
	mustEmbedUnimplementedSnapshotServiceServer()
}

func RegisterSnapshotServiceServer(s grpc.ServiceRegistrar, srv SnapshotServiceServer) {
	s.RegisterService(&SnapshotService_ServiceDesc, srv)
}

func _SnapshotService_CreateSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotServiceServer).CreateSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnapshotService_CreateSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotServiceServer).CreateSnapshot(ctx, req.(*CreateSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnapshotService_GetSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotServiceServer).GetSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnapshotService_GetSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotServiceServer).GetSnapshot(ctx, req.(*GetSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnapshotService_ListSnapshots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSnapshotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotServiceServer).ListSnapshots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnapshotService_ListSnapshots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotServiceServer).ListSnapshots(ctx, req.(*ListSnapshotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnapshotService_DeleteSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotServiceServer).DeleteSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnapshotService_DeleteSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotServiceServer).DeleteSnapshot(ctx, req.(*DeleteSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnapshotService_RestoreSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotServiceServer).RestoreSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnapshotService_RestoreSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotServiceServer).RestoreSnapshot(ctx, req.(*RestoreSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SnapshotService_ServiceDesc is the grpc.ServiceDesc for SnapshotService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SnapshotService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "seaweedfs.block.control.SnapshotService",
	HandlerType: (*SnapshotServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSnapshot",
			Handler:    _SnapshotService_CreateSnapshot_Handler,
		},
		{
			MethodName: "GetSnapshot",
			Handler:    _SnapshotService_GetSnapshot_Handler,
		},
		{
			MethodName: "ListSnapshots",
			Handler:    _SnapshotService_ListSnapshots_Handler,
		},
		{
			MethodName: "DeleteSnapshot",
			Handler:    _SnapshotService_DeleteSnapshot_Handler,
		},
		{
			MethodName: "RestoreSnapshot",
			Handler:    _SnapshotService_RestoreSnapshot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "control.proto",
}

const (
	SnapshotBackupService_ExportSnapshotBackup_FullMethodName = "/seaweedfs.block.control.SnapshotBackupService/ExportSnapshotBackup"
	SnapshotBackupService_GetSnapshotBackup_FullMethodName    = "/seaweedfs.block.control.SnapshotBackupService/GetSnapshotBackup"
	SnapshotBackupService_ListSnapshotBackups_FullMethodName  = "/seaweedfs.block.control.SnapshotBackupService/ListSnapshotBackups"
	SnapshotBackupService_ImportSnapshotBackup_FullMethodName = "/seaweedfs.block.control.SnapshotBackupService/ImportSnapshotBackup"
)

// SnapshotBackupServiceClient is the client API for SnapshotBackupService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SnapshotBackupServiceClient interface {
	ExportSnapshotBackup(ctx context.Context, in *ExportSnapshotBackupRequest, opts ...grpc.CallOption) (*SnapshotBackupRecord, error)
	GetSnapshotBackup(ctx context.Context, in *GetSnapshotBackupRequest, opts ...grpc.CallOption) (*SnapshotBackupRecord, error)
	ListSnapshotBackups(ctx context.Context, in *ListSnapshotBackupsRequest, opts ...grpc.CallOption) (*ListSnapshotBackupsResponse, error)
	ImportSnapshotBackup(ctx context.Context, in *ImportSnapshotBackupRequest, opts ...grpc.CallOption) (*SnapshotRecord, error)
}

type snapshotBackupServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSnapshotBackupServiceClient(cc grpc.ClientConnInterface) SnapshotBackupServiceClient {
	return &snapshotBackupServiceClient{cc}
}

func (c *snapshotBackupServiceClient) ExportSnapshotBackup(ctx context.Context, in *ExportSnapshotBackupRequest, opts ...grpc.CallOption) (*SnapshotBackupRecord, error) {
	out := new(SnapshotBackupRecord)
	err := c.cc.Invoke(ctx, SnapshotBackupService_ExportSnapshotBackup_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snapshotBackupServiceClient) GetSnapshotBackup(ctx context.Context, in *GetSnapshotBackupRequest, opts ...grpc.CallOption) (*SnapshotBackupRecord, error) {
	out := new(SnapshotBackupRecord)
	err := c.cc.Invoke(ctx, SnapshotBackupService_GetSnapshotBackup_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snapshotBackupServiceClient) ListSnapshotBackups(ctx context.Context, in *ListSnapshotBackupsRequest, opts ...grpc.CallOption) (*ListSnapshotBackupsResponse, error) {
	out := new(ListSnapshotBackupsResponse)
	err := c.cc.Invoke(ctx, SnapshotBackupService_ListSnapshotBackups_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snapshotBackupServiceClient) ImportSnapshotBackup(ctx context.Context, in *ImportSnapshotBackupRequest, opts ...grpc.CallOption) (*SnapshotRecord, error) {
	out := new(SnapshotRecord)
	err := c.cc.Invoke(ctx, SnapshotBackupService_ImportSnapshotBackup_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SnapshotBackupServiceServer is the server API for SnapshotBackupService service.
// All implementations must embed UnimplementedSnapshotBackupServiceServer
// for forward compatibility
type SnapshotBackupServiceServer interface {
	ExportSnapshotBackup(context.Context, *ExportSnapshotBackupRequest) (*SnapshotBackupRecord, error)
	GetSnapshotBackup(context.Context, *GetSnapshotBackupRequest) (*SnapshotBackupRecord, error)
	ListSnapshotBackups(context.Context, *ListSnapshotBackupsRequest) (*ListSnapshotBackupsResponse, error)
	ImportSnapshotBackup(context.Context, *ImportSnapshotBackupRequest) (*SnapshotRecord, error)
	mustEmbedUnimplementedSnapshotBackupServiceServer()
}

// UnimplementedSnapshotBackupServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSnapshotBackupServiceServer struct {
}

func (UnimplementedSnapshotBackupServiceServer) ExportSnapshotBackup(context.Context, *ExportSnapshotBackupRequest) (*SnapshotBackupRecord, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExportSnapshotBackup not implemented")
}
func (UnimplementedSnapshotBackupServiceServer) GetSnapshotBackup(context.Context, *GetSnapshotBackupRequest) (*SnapshotBackupRecord, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSnapshotBackup not implemented")
}
func (UnimplementedSnapshotBackupServiceServer) ListSnapshotBackups(context.Context, *ListSnapshotBackupsRequest) (*ListSnapshotBackupsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSnapshotBackups not implemented")
}
func (UnimplementedSnapshotBackupServiceServer) ImportSnapshotBackup(context.Context, *ImportSnapshotBackupRequest) (*SnapshotRecord, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportSnapshotBackup not implemented")
}
func (UnimplementedSnapshotBackupServiceServer) mustEmbedUnimplementedSnapshotBackupServiceServer() {}

// UnsafeSnapshotBackupServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SnapshotBackupServiceServer will
// result in compilation errors.
type UnsafeSnapshotBackupServiceServer interface {
	mustEmbedUnimplementedSnapshotBackupServiceServer()
}

func RegisterSnapshotBackupServiceServer(s grpc.ServiceRegistrar, srv SnapshotBackupServiceServer) {
	s.RegisterService(&SnapshotBackupService_ServiceDesc, srv)
}

func _SnapshotBackupService_ExportSnapshotBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportSnapshotBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotBackupServiceServer).ExportSnapshotBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnapshotBackupService_ExportSnapshotBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotBackupServiceServer).ExportSnapshotBackup(ctx, req.(*ExportSnapshotBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnapshotBackupService_GetSnapshotBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSnapshotBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotBackupServiceServer).GetSnapshotBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnapshotBackupService_GetSnapshotBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotBackupServiceServer).GetSnapshotBackup(ctx, req.(*GetSnapshotBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnapshotBackupService_ListSnapshotBackups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSnapshotBackupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotBackupServiceServer).ListSnapshotBackups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnapshotBackupService_ListSnapshotBackups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotBackupServiceServer).ListSnapshotBackups(ctx, req.(*ListSnapshotBackupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnapshotBackupService_ImportSnapshotBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportSnapshotBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotBackupServiceServer).ImportSnapshotBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnapshotBackupService_ImportSnapshotBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotBackupServiceServer).ImportSnapshotBackup(ctx, req.(*ImportSnapshotBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SnapshotBackupService_ServiceDesc is the grpc.ServiceDesc for SnapshotBackupService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SnapshotBackupService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "seaweedfs.block.control.SnapshotBackupService",
	HandlerType: (*SnapshotBackupServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExportSnapshotBackup",
			Handler:    _SnapshotBackupService_ExportSnapshotBackup_Handler,
		},
		{
			MethodName: "GetSnapshotBackup",
			Handler:    _SnapshotBackupService_GetSnapshotBackup_Handler,
		},
		{
			MethodName: "ListSnapshotBackups",
			Handler:    _SnapshotBackupService_ListSnapshotBackups_Handler,
		},
		{
			MethodName: "ImportSnapshotBackup",
			Handler:    _SnapshotBackupService_ImportSnapshotBackup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "control.proto",
}
