{{- if and .Values.chap.enabled .Values.chap.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.chap.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "seaweed-block.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.chap.usernameKey }}: {{ required "chap.username is required when chap.enabled=true" .Values.chap.username | quote }}
  {{ .Values.chap.secretKey }}: {{ required "chap.secret is required when chap.enabled=true" .Values.chap.secret | quote }}
{{- if ne .Values.appNamespace .Release.Namespace }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.chap.secretName }}
  namespace: {{ .Values.appNamespace }}
  labels:
    {{- include "seaweed-block.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.chap.usernameKey }}: {{ .Values.chap.username | quote }}
  {{ .Values.chap.secretKey }}: {{ .Values.chap.secret | quote }}
{{- end }}
{{- end }}
