{{- if and .Values.frontendPublicationExecutor.create .Values.frontendPublicationExecutor.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "seaweed-block.fullname" . }}-frontend-publication-executor
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "seaweed-block.fullname" . }}-frontend-publication-executor
rules:
  - apiGroups: ["block.seaweedfs.com"]
    resources: ["swblockfrontendpublications"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["block.seaweedfs.com"]
    resources: ["swblockfrontendpublications/status"]
    verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "seaweed-block.fullname" . }}-frontend-publication-executor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "seaweed-block.fullname" . }}-frontend-publication-executor
subjects:
  - kind: ServiceAccount
    name: {{ include "seaweed-block.fullname" . }}-frontend-publication-executor
    namespace: {{ .Release.Namespace }}
{{- end }}
