{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "seaweed-block.fullname" . }}-csi
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "seaweed-block.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "seaweed-block.fullname" . }}-master
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "seaweed-block.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "seaweed-block.fullname" . }}-master-launcher
  labels:
    {{- include "seaweed-block.labels" . | nindent 4 }}
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "seaweed-block.fullname" . }}-master-launcher
  labels:
    {{- include "seaweed-block.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "seaweed-block.fullname" . }}-master
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "seaweed-block.fullname" . }}-master-launcher
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "seaweed-block.fullname" . }}-csi-controller
  labels:
    {{- include "seaweed-block.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes", "persistentvolumeclaims", "nodes"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses", "volumeattachments", "volumeattachments/status", "csinodes", "csidrivers"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "seaweed-block.fullname" . }}-csi-controller
  labels:
    {{- include "seaweed-block.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "seaweed-block.fullname" . }}-csi
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "seaweed-block.fullname" . }}-csi-controller
{{- end }}
